
-- Tabla USUARIO
CREATE TABLE USUARIO (
    idUsuario SERIAL PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    apellido VARCHAR(50) NOT NULL,
    fechaNacimiento DATE NOT NULL,
    genero VARCHAR(10) NOT NULL,
    email VARCHAR(50),
    telefono BIGINT,
    contrasena VARCHAR(50) NOT NULL,
    premium BOOLEAN
);

-- Tabla DIRECCIONES_FRECUENTES
CREATE TABLE DIRECCIONES_FRECUENTES (
    id SERIAL PRIMARY KEY,
    idUsuario INT NOT NULL REFERENCES USUARIO(idUsuario) ON DELETE CASCADE ON UPDATE CASCADE,
    nombre VARCHAR(50) NOT NULL,
    latitud VARCHAR(255) NOT NULL,
    longitud VARCHAR(255) NOT NULL
);

-- Tabla METODOS_DE_PAGO
CREATE TABLE METODOS_DE_PAGO (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    url_api VARCHAR(500) NOT NULL
);

-- Tabla EMPRESA
CREATE TABLE EMPRESA (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    url_api VARCHAR(200) NOT NULL
);

-- Tabla VIAJES
CREATE TABLE VIAJES (
    id SERIAL PRIMARY KEY,
    idUsuario INT NOT NULL REFERENCES USUARIO(idUsuario) ON DELETE CASCADE ON UPDATE CASCADE,
    origen VARCHAR(200) NOT NULL,
    destino VARCHAR(200) NOT NULL,
    fecha DATE NOT NULL,
    estado VARCHAR(50) NOT NULL,
    hora TIME NOT NULL,
    idPago INT,
    idEmpresa INT NOT NULL REFERENCES EMPRESA(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Tabla PAGOS
CREATE TABLE PAGOS (
    idPago SERIAL PRIMARY KEY,
    idViaje INT NOT NULL REFERENCES VIAJES(id) ON DELETE CASCADE ON UPDATE CASCADE,
    costo DECIMAL(10,2) NOT NULL,
    fechaPago DATE NOT NULL,
    idMetodoPago INT NOT NULL REFERENCES METODOS_DE_PAGO(id) ON DELETE CASCADE ON UPDATE CASCADE,
    idPrecio INT NOT NULL
);

-- Tabla CONSULTAS
CREATE TABLE CONSULTAS (
    id SERIAL PRIMARY KEY,
    idUsuario INT NOT NULL REFERENCES USUARIO(idUsuario) ON DELETE CASCADE ON UPDATE CASCADE,
    fecha DATE NOT NULL,
    hora TIME NOT NULL,
    origenLatitud VARCHAR(255) NOT NULL,
    origenLongitud VARCHAR(255) NOT NULL,
    destinoLatitud VARCHAR(255) NOT NULL,
    destinoLongitud VARCHAR(255) NOT NULL
);

-- Tabla PREFERENCIAS
CREATE TABLE PREFERENCIAS (
    id SERIAL PRIMARY KEY,
    idUsuario INT NOT NULL REFERENCES USUARIO(idUsuario) ON DELETE CASCADE ON UPDATE CASCADE,
    modo_transporte_preferido VARCHAR(255) NOT NULL,
    metodoPagoPreferido VARCHAR(255) NOT NULL
);

-- Tabla PRECIOS
CREATE TABLE PRECIOS (
    id SERIAL PRIMARY KEY,
    idUsuario INT NOT NULL REFERENCES USUARIO(idUsuario) ON DELETE CASCADE ON UPDATE CASCADE,
    idEmpresa INT NOT NULL REFERENCES EMPRESA(id) ON DELETE CASCADE ON UPDATE CASCADE,
    origenLatitud VARCHAR(255) NOT NULL,
    origenLongitud VARCHAR(255) NOT NULL,
    destinoLatitud VARCHAR(255) NOT NULL,
    destinoLongitud VARCHAR(255) NOT NULL
);

-- Tabla RESULTADOS_CONSULTA
CREATE TABLE RESULTADOS_CONSULTA (
    id SERIAL PRIMARY KEY,
    idConsulta INT NOT NULL REFERENCES CONSULTAS(id) ON DELETE CASCADE ON UPDATE CASCADE,
    idEmpresa INT NOT NULL REFERENCES EMPRESA(id) ON DELETE CASCADE ON UPDATE CASCADE,
    precio_estimado DECIMAL(18,0) NOT NULL,
    tiempo_estimado TIME NOT NULL
);
